ARG BASE_TAG=ubuntu-16.04
FROM pizzafactory0contorno/piatto:$BASE_TAG

RUN sudo apt-get update && sudo apt-get upgrade -y && \
    sudo apt-get install -y wget bzip2 build-essential ruby && \
    wget http://ev3rt-git.github.io/public/ev3rt-prepare-ubuntu.sh && \
    yes 1 | sudo bash -x ev3rt-prepare-ubuntu.sh && \
    sudo rm ev3rt-prepare-ubuntu.sh && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*
    
