#!/bin/bash
set -eu

if [ -z "${DOCKERFILE_PATH+UNDEF}" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

docker build --build-arg BASE_TAG=${DOCKER_TAG} -t $IMAGE_NAME ${DOCKERFILE_PATH_ARG} .

